# Generated by Django 5.1.3 on 2024-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='users/default.jpg', upload_to='users/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
